name: Makefile CI (libctrpf)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: pablomk7/libctrpf:0.8.0

    steps:
    - uses: actions/checkout@v2
      
    - name: Build Plugin
      run: make
      
    - name: Upload Plugin
      uses: actions/upload-artifact@v4
      with:
        name: Plugin 3GX File
        path: Vapecord.3gx
    
    - name: Upload Plugin ELF
      uses: actions/upload-artifact@v4
      with:
        name: Plugin ELF File
        path: Vapecord.elf
